---
title: Grimoire

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  grimoire:
    output: true

defaults:
  - scope:
      path: '_grimoire'
    values:
      layout: bin
